2023-03-06 20:33:00,262 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1044f99d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:33:00,365 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104929d10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:33:00,387 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10469a110>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:34:00,013 INFO: Checking website status at 2023-03-06 19:34:00.013207 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:35:00,007 INFO: Checking website status at 2023-03-06 19:35:00.007784 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:35:00,026 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104928150>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,040 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104906690>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,058 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1049026d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,171 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104905250>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,207 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10492a290>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,225 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10491a090>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,304 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10469a050>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:35:00,324 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104917350>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,008 INFO: Checking website status at 2023-03-06 19:36:00.008627 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:36:00,033 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104917150>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,053 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10469b690>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,087 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10492b790>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,173 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104919550>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,213 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104905cd0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,230 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1049075d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,313 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10491b6d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:36:00,356 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104904a50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:37:00,008 INFO: Checking website status at 2023-03-06 19:37:00.008434 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:37:00,033 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104916410>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:37:00,052 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1049143d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:37:00,088 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1046a3b90>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
