2023-03-06 20:45:00,087 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083a3450>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,127 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083ac150>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,224 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083bb590>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,271 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10837d790>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,294 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083af0d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,397 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083a3210>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:45:00,419 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083b7750>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,012 INFO: Checking website status at 2023-03-06 19:48:00.011979 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:48:00,041 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083c94d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,064 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083cb310>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,104 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083ca6d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,190 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x108360c50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,226 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083b4490>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,239 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083a28d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,320 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083ac990>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:48:00,337 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083bb050>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,018 INFO: Checking website status at 2023-03-06 19:51:00.017903 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:150]
2023-03-06 20:51:00,039 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083aca10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,057 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d58d50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,093 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083b5950>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,179 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083ca250>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,216 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083767d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,235 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083b7690>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,329 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083c9810>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
2023-03-06 20:51:00,386 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1083afe10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:161]
